services:
  - name: crop-system
    type: web
    runtime: python
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.headless true
    plan: free
